
// const { data, error, isLoading } = useGetProductsApiByNameQuery('bulbasaur')
// import { useGetProductsApiByNameQuery } from "./redux/ProductsApi"
// export const basic="http://127.0.0.1:8000/api"
export const registerUrl="register"
export const LoginUrl="login"
export const LogOutUrl="logout"
export const usersUrl="users"
export const userUrl="user"
// export const cat="category"
// export const cats="categories"
// export const pros="products"
// export const pro="product"
// export const latestSale="latest-sale"
// export const topRated="top-rated"
// export const latest="latest"
// export const googleCallUrl="auth/google/callback"
// export const cart="cart"
// ---------------------------------------------------------------------------------
export const basic="https://dummyjson.com"
// export const registerUrl="register"
// export const LoginUrl="login"
// export const LogOutUrl="logout"
// export const usersUrl="users"
// export const userUrl="user"
export const curentUserUrl="auth/me"
export const cat="category"
export const cats="categories"
export const pros="products"
export const pro="product"
export const latestSale="latest-sale"
export const topRated="top-rated"
export const latest="latest"
export const googleCallUrl="auth/google/callback"
export const cart="cart"